public final class Constants {
    public static final String[]
            INCIDENT_ARSON = {"arson","ablaze","blaze","burn","burning","fire","fires"},
            INCIDENT_ATTACK = {"murder","murdered","murderer","murderers","murdering","murders","gun","bullet",""},
            INCIDENT_BOMBING = {"bomb","bomber","bombers","bombing","bombings","bombs","detonate","detonated","detonates","dynamite",
                    "explode","exploded","explodes","explosion","explosions","explosive","explosives"},
            INCIDENT_KIDNAPPING = {"abduct","abducting","abduction","abductions","abductors","kidnap","kidnapped","kidnapper",
                    "kidnappers","kidnapping","kidnappings"},
            INCIDENT_ROBBERY = {"rob","robberies","robbery","robbing","robs"},
    			WEAPONS= {"MACHINE-GUN","DYNAMITE STICKS","DYNAMITE","GRENADES","MACHINEGUNS","BULLET","HELICOPTER GUNSHIPS","GUNSHIPS"
    					,"C-47 AIRCRAFT","HEAVY CALIBER WEAPONS","AK-47S","M-16S","MACHINEGUNS IN TRIPODS","MACHINEGUNS",".22 CALIBER GUN"
    					,"CALIBER GUN","HELICOPTER GUNSHIP","MORTAR","MM WEAPON","WEAPON","GRENADE"
    					,"MACHINEGUN","BULLETS","C-47 AIRCRAFTS","AIRCRAFT","AIRCRAFTS","HEAVY CALIBER WEAPON","GUNS","MORTARS"
    					,"BOMB","BOMB BLAST","BOMBS","DYNAMITE CHARGE","DYNAMITE","EXPLOSIVE DEVICES", "CHARGE OF DYNAMITE"
    					,"FOUR BOMBS","EXPLOSIVE CHARGES","ROCKET","BOMB SET IN AN ICE CREAM","DYNAMITE CHARGE","POWERFUL BOMB","GRENADE","CAR BOMB","PACKAGES OF DYNAMITE EXPLOSIVES","TNT", "TRUCK","A BOMB","MINE"
    					},
    			TARGET= {"BUILDING","EMBASSY","SCHOOL","TOWER","UNIVERSITY","OFFICE","BUILDINGS","EMBASSIES","SCHOOLS","UNIVERSITIES","OFFICES","TOWERS"
    					,"CENTER","CENTERS","SHOPPING","SHOP","SHOPS","FESTIVAL","FESTIVALS","TRAIN","TRAINS","AIRPLANE","AIRPLANES","TERMINAL","TERMINALS","AIRPORT","AIRPORTS"
    					,"TRANSPORTAION","TRANSPORTATIONS","WEARHOUSE","WEARHOUSES","BANK","BANKS"
    					,"MISSIONARIES","MISSIONARY","VEHICLE","CAR","CARS","VEHICLES","TRUCK","TRUCKS","BUS","BUSES"
    					,"STATION","STATIONS","FACTORY","FACTORIES","PLANE","PLANES","HOSPITAL","HOSPITALS","HOUSES","HOUSE","APARTMENT","APARTMENTS"
    					,"POLICE","POLICES","STUDENTS","STUDENT","HOTEL","HOTELS","TRANSFORMER","TRANSFORMERS","RESTAURANT","MEDICAL CLINICS","CONSTRUCTION SITE","CONSTRUCTION SITES",
    					"FACILITIES","FACILITY","ORGANIZATION","ORGANIZATIONS","HEADQUARTERS","HEADQUARTER","HOME","HOMES","FENASTRAS","FENASTRAS","RESIDENCE","MINISTATION",
    					"MINISTATIONS","CINEMA","THEATER","MOVIE","STORE","STORES"};
    			
}
//MACHINE-GUN->ATTACK
//DYNAMITE STICKS / DYNAMITE->BOMBING
//ATTACK->GRENADES/MACHINEGUNS/BULLET/HELICOPTER GUNSHIPS/C-47 AIRCRAFT/ARTILLERY/HEAVY CALIBER WEAPONS/AK-47S/M-16S/MACHINEGUNS IN TRIPODS/MACHINEGUNS/.22 CALIBER GUN/HELICOPTER GUNSHIP/MORTAR/9-MM WEAPONS/GRENADE/MACHINEGUN/BULLETS/HELICOPTER GUNSHIP/C-47 AIRCRAFTS/AIRCRAFT/AIRCRAFTS/HEAVY CALIBER WEAPON/ARTILLERIES/GUNS/.22 CALIBER GUNS/MORTARS/9-MM WEAPON

//BOMBING->BOMB/BOMB BLAST/BOMBS/DYNAMITE CHARGE/DYNAMITE/EXPLOSIVE DEVICES/CHARGE OF DYNAMITE/FOUR BOMBS/EXPLOSIVE CHARGES/ROCKET / BOMB SET IN AN ICE CREAM/DYNAMITE CHARGE/POWERFUL BOMB/GRENADE/CAR BOMB/PACKAGES OF DYNAMITE/EXPLOSIVES / TNT/DYNAMITE / TRUCK/A BOMB/MINE

